import { Main } from './templates/main.js'
import { Dot } from './components/dot.js'
import { Nav } from './components/nav.js'
import { Grid } from './components/grid.js'
import { Footer } from './components/footer.js'

/* global Vue */
new Vue({
  el: '#app',
  data: function() {
    return {
      tweets: [
      {
        name: "/u/arswaw",
        handle: "@arswaw",
        job: "Web Developer",
        bio: "I am the greatest programmer in the world. My code is studied the world over by the foremost programmers."
      },
     {
       "name": "Sarah McBride",
       "handle": "handle",
       "job": "job",
       "bio": "This was generated by a computer."
     },
     {
       "name": "Derrick Lowe",
       "handle": "handle",
       "job": "job",
       "bio": "bio"
     },
     {
       "name": "Jane Dennis",
       "handle": "handle",
       "job": "job",
       "bio": "bio"
     },
     {
       "name": "Marvin Morris",
       "handle": "handle",
       "job": "job",
       "bio": "bio"
     },
     {
       "name": "Dorothy Lee",
       "handle": "handle",
       "job": "job",
       "bio": "bio"
     },
     {
       "name": "Joel Chavez",
       "handle": "handle",
       "job": "job",
       "bio": "bio"
     },
     {
       "name": "Rose Allison",
       "handle": "handle",
       "job": "job",
       "bio": "bio"
     },
     {
       "name": "Cecelia Holland",
       "handle": "handle",
       "job": "job",
       "bio": "bio"
     },
     {
       "name": "Lottie Bailey",
       "handle": "handle",
       "job": "job",
       "bio": "bio"
     },
     {
       "name": "Ricardo Terry",
       "handle": "handle",
       "job": "job",
       "bio": "bio"
     },
     {
       "name": "Inez Harrison",
       "handle": "handle",
       "job": "job",
       "bio": "bio"
     }
      ]
    }
  },
  components: {
    'dot': Dot,
    'navbar': Nav,
    'grid': Grid,
    'footer-section': Footer
  },
  template: Main
})